
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Elfen.l1ed
      MYSQL_DATABASE: subApp
      MYSQL_PASSWORD: Elfen.l1ed
    ports:
      - "3306"

  rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
  asscache:
      build: .
      ports:
        - "8081"
      depends_on:
        - rabbitmq
      environment:
        - SPRING_PROFILES_ACTIVE=default
